# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Praxis für emotionale Gesundheit
tagline: Sprechen wir darüber
email: praxis@tanja-knappe.de
tel: 08442 968587
tel_link: tel:498442968587
description: ''
url: 'https://www.tanja-knappe.de'
logo: ''
lang: de
company: Praxis für emotionale Gesundheit
ceo: Tanja Knappe
street: Josef-Reindl-Str.29
postal_code: 85283
city: Wolnzach
show_drafts: false
collections_dir: collections
collections:
  posts:
    permalink: /blog/:categories/:title
exclude: [webpack, package.json, package-lock.json]
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
# google_site_verification: 'gkmYUF0HK6isbGz66WJLWSklOIJC196zj_4AGM9QL8w'

pagination:
  enabled: true
  per_page: 4
  permalink: '/:num/'
  title: 'Blog'
  limit: 0
  extension: ''
  sort_field: 'date'
  sort_reverse: true

jekyll-archives:
  enabled: 
    - categories
  layouts: 
    category: categories
  permalinks:
    category: '/blog/:name/'

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
      sidebar: primary
      prefooter: true

sass:
  style: compressed
  sourcemap: never

# Build settings
plugins:
  - jekyll-pug
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-archives

jekyll-pug:
  minify: true
