backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
media_library:
  name: cloudinary
  output_filename_only: false
  config:
    cloud_name: dc5q25fmj
    api_key: 128385357995845
collections:
  - name: "config"
    label: "Einstellungen"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "navigation"
        file: "_data/navigation.yml"
        fields:
          - label: "Links"
            name: "nav"
            widget: "list"
            fields:
              - {label: Name, name: title, widget: string}
              - {label: Link, name: url, widget: string, required: false}
              - label: Unterseiten
                name: children
                widget: list
                required: false
                fields:
                  - {label: Name, name: title, widget: string}
                  - {label: Link, name: url, widget: string}

      - label: "Kurstermine"
        name: "course_info"
        file: "_data/course_info.yml"
        fields:
          - label: "Kurstermine"
            name: "courses"
            widget: "list"
            fields:
              - {label: Titel, name: title, widget: string}
              - {label: Datum, name: date, widget: datetime, timeFormat: false, format: DD.MM.YYYY}
              - {label: Uhrzeit, name: time, widget: string}
              - {label: Kursdauer, name: duration, widget: string}
              - {label: Preis, name: price, widget: number}
              - {label: Extra Info, name: extra_info, widget: string, required: false, hint: 'Wird unter der Adresse in der Spalte "Kursort" angezeigt'}
              - label: Ort
                name: location
                widget: object
                fields:
                  - {label: Namenszusatz, name: name, widget: string, required: false, hint: 'z.B. "Sonnenwirt"'}
                  - {label: Straße, name: street, widget: string}
                  - {label: PLZ, name: postal_code, widget: number}
                  - {label: Ort, name: city, widget: string}
                  - {label: Telefon, name: tel, widget: string, required: false}
                  - {label: Email, name: email, widget: string, required: false}
                  - {label: Institution, name: title, widget: string, hint: 'z.B. "VHS Wolnzach"'}
              - label: Anmeldung
                name: application
                widget: object
                fields:
                  - {label: Ort, name: institution, widget: string}
                  - {label: Telefon, name: tel, widget: string}
                  - {label: Email, name: email, widget: string}
                  - {label: Anmeldung offen, name: open, widget: boolean}

      - label: "Preise"
        name: "propositions"
        file: "_data/propositions.yml"
        fields:
          - label: "Preise"
            name: "items"
            widget: "object"
            fields:
              - label: Erstgespräch
                name: anamnesis
                widget: object
                fields:
                  - {label: Dauer, name: duration, widget: number}
                  - {label: Preis, name: price, widget: number}
              - label: Coaching
                name: coaching
                widget: object
                fields:
                  - {label: Dauer, name: duration, widget: number}
                  - {label: Preis, name: price, widget: number}
              - label: Psychotherapie
                name: therapy
                widget: object
                fields:
                  - label: Kurz
                    name: short
                    widget: object
                    fields:
                      - {label: Dauer, name: duration, widget: number}
                      - {label: Preis, name: price, widget: number}
                  - label: Lang
                    name: long
                    widget: object
                    fields:
                      - {label: Dauer, name: duration, widget: number}
                      - {label: Preis, name: price, widget: number}
              - label: Autogenes Training
                name: autogenic_training
                widget: object
                fields:
                  - label: Einzeltraining
                    name: private
                    widget: object
                    fields:
                      - {label: Dauer, name: duration, widget: string}
                      - {label: Preis, name: price, widget: number}
                  - label: Gruppentraining
                    name: group
                    widget: object
                    fields:
                      - {label: Dauer, name: duration, widget: string}
                      - {label: Preis, name: price, widget: number}
    
  - name: 'blog'
    label: 'Blog Einträge'
    label_singular: 'Blog Eintrag'
    folder: 'collections/_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog-post'}
      - {label: 'Titel', name: 'title', widget: 'string'}
      - {label: 'Kategorien', name: 'categories', widget: 'list'}
      - {label: 'Datum', name: 'date', widget: 'datetime'}
      - label: 'Bild'
        name: 'featured_image'
        widget: 'image'
        media_library:
          name: cloudinary
          output_filename_only: true
      - label: 'Inhalt' 
        name: 'body'
        widget: 'markdown'
